/*
 * Copyright (C) 2017 Milton Cavazos
 *
 * Este programa es de código libre; usted podrá instalar y/o
 * utilizar una copia del programa de computación en una computadora compatible,
 * limitándose al número permitido de computadoras.
 */
package dis.software.pos.jforms.components;

/**
 * Formulario para la sincronización
 * @author Milton Cavazos
 */
public class SyncComponent extends javax.swing.JFrame
{

    /**
     * Creación de nuevo formulario SyncComponent
     */
    public SyncComponent()
    {
        
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblSyncInventory = new javax.swing.JLabel();
        jbtnSyncInventory = new javax.swing.JButton();
        jlblSyncProduct = new javax.swing.JLabel();
        jbtnSyncProduct = new javax.swing.JButton();
        jlblSyncPromotion = new javax.swing.JLabel();
        jbtnSyncPromotion = new javax.swing.JButton();
        jlblSyncPurchase = new javax.swing.JLabel();
        jbtnSyncPurchase = new javax.swing.JButton();
        jlblSyncSale = new javax.swing.JLabel();
        jbtnSyncSale = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblSyncInventory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblSyncInventory.setText("Sincronizar inventario");

        jbtnSyncInventory.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSyncInventory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSyncInventory.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSyncInventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sync-b.png"))); // NOI18N
        jbtnSyncInventory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSyncInventory.setIconTextGap(8);
        jbtnSyncInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSyncInventoryMouseClicked(evt);
            }
        });

        jlblSyncProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblSyncProduct.setText("Sincronizar productos");

        jbtnSyncProduct.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSyncProduct.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSyncProduct.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSyncProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sync-b.png"))); // NOI18N
        jbtnSyncProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSyncProduct.setIconTextGap(8);
        jbtnSyncProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSyncProductMouseClicked(evt);
            }
        });

        jlblSyncPromotion.setText("Sincronizar promociones");
        jlblSyncPromotion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jbtnSyncPromotion.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSyncPromotion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSyncPromotion.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSyncPromotion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sync-b.png"))); // NOI18N
        jbtnSyncPromotion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSyncPromotion.setIconTextGap(8);
        jbtnSyncPromotion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSyncPromotionMouseClicked(evt);
            }
        });

        jlblSyncPurchase.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblSyncPurchase.setText("Sincronizar compras");

        jbtnSyncPurchase.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSyncPurchase.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSyncPurchase.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSyncPurchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sync-b.png"))); // NOI18N
        jbtnSyncPurchase.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSyncPurchase.setIconTextGap(8);
        jbtnSyncPurchase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSyncPurchaseMouseClicked(evt);
            }
        });

        jlblSyncSale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblSyncSale.setText("Sincronizar ventas");

        jbtnSyncSale.setBackground(new java.awt.Color(204, 204, 204));
        jbtnSyncSale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSyncSale.setForeground(new java.awt.Color(0, 0, 0));
        jbtnSyncSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sync-b.png"))); // NOI18N
        jbtnSyncSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSyncSale.setIconTextGap(8);
        jbtnSyncSale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSyncSaleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblSyncSale)
                    .addComponent(jlblSyncInventory)
                    .addComponent(jlblSyncProduct)
                    .addComponent(jlblSyncPromotion)
                    .addComponent(jlblSyncPurchase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnSyncInventory)
                    .addComponent(jbtnSyncProduct)
                    .addComponent(jbtnSyncPromotion)
                    .addComponent(jbtnSyncPurchase)
                    .addComponent(jbtnSyncSale))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jlblSyncInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jbtnSyncInventory))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jlblSyncProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jbtnSyncProduct))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlblSyncPromotion, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtnSyncPromotion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblSyncPurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnSyncPurchase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblSyncSale, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnSyncSale))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSyncInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSyncInventoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSyncInventoryMouseClicked

    private void jbtnSyncProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSyncProductMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSyncProductMouseClicked

    private void jbtnSyncPromotionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSyncPromotionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSyncPromotionMouseClicked

    private void jbtnSyncPurchaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSyncPurchaseMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSyncPurchaseMouseClicked

    private void jbtnSyncSaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSyncSaleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSyncSaleMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnSyncInventory;
    private javax.swing.JButton jbtnSyncProduct;
    private javax.swing.JButton jbtnSyncPromotion;
    private javax.swing.JButton jbtnSyncPurchase;
    private javax.swing.JButton jbtnSyncSale;
    private javax.swing.JLabel jlblSyncInventory;
    private javax.swing.JLabel jlblSyncProduct;
    private javax.swing.JLabel jlblSyncPromotion;
    private javax.swing.JLabel jlblSyncPurchase;
    private javax.swing.JLabel jlblSyncSale;
    // End of variables declaration//GEN-END:variables
}
