/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dis.software.pos.jforms;

import dis.software.pos.ApplicationSession;
import dis.software.pos.entities.ProfileModule;
import dis.software.pos.entities.User;
import java.awt.Component;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Formulario principal
 * @author Milton Cavazos
 */
public class MainJFrame extends javax.swing.JFrame
{

    private static Logger logger = LogManager.getLogger(MainJFrame.class.getSimpleName());
    
    /**
     * Creación de nuevo formulario MainJFrame
     */
    public MainJFrame()
    {
        initComponents();
        
        MainJFrame mainJFrame = this;
        mainJFrame.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                if (JOptionPane.showConfirmDialog(mainJFrame, "¿Estás seguro que deseas salir del sistema?",
                    "Seleccionar una opción", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
                {
                    System.exit(0);
                }
            }
        });
        
        jmItemExit.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, ActionEvent.CTRL_MASK));
        
        User user = ApplicationSession.getUser();
        if (user.getProfile() == null)
        {
            jMenuUser.setVisible(false);
            jMenuProfile.setVisible(false);
            return;
        }
        List<ProfileModule> profileModules = new ArrayList<>(user.getProfile().getProfileModules());
        profileModules.stream().forEach(profileModule ->
        {
            if ("MOD-001".equals(profileModule.getModule().getCode()))
            {
                if (!profileModule.getPrivileges().getViewProperty())
                {
                    jmItemUserView.setVisible(false);
                }
            }
        });
    }
    
    private <T extends JInternalFrame> Boolean isWindowOpened(Class<T> window)
    {
        Boolean isOpened = Boolean.FALSE;
        for (Component component : desktopPane.getComponents())
        {
            if (window.isInstance(component))
            {
                isOpened = Boolean.TRUE;
                break;
            }
        }
        return isOpened;
    }
    
    private <T extends JInternalFrame> Component getWindow(Class<T> window)
    {
        Component openWindow = null;
        for (Component component : desktopPane.getComponents())
        {
            if (window.isInstance(component))
            {
                openWindow = component;
                break;
            }
        }
        return openWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jpanelToolbar = new javax.swing.JPanel();
        jbtnInventoryDetailShortcut = new javax.swing.JButton();
        jbtnSale = new javax.swing.JButton();
        jbtnProductViewShortcut = new javax.swing.JButton();
        jbtnCash = new javax.swing.JButton();
        jbtnReport = new javax.swing.JButton();
        jbtnSynchShortcut = new javax.swing.JButton();
        jlblCurrentDate = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenuSystem = new javax.swing.JMenu();
        jmItemExit = new javax.swing.JMenuItem();
        jMenuUser = new javax.swing.JMenu();
        jmItemUserView = new javax.swing.JMenuItem();
        jmItemUserCreate = new javax.swing.JMenuItem();
        jmItemUserEdit = new javax.swing.JMenuItem();
        jmItemUserDelete = new javax.swing.JMenuItem();
        jMenuProfile = new javax.swing.JMenu();
        jmItemProfileView = new javax.swing.JMenuItem();
        jmItemProfileCreate = new javax.swing.JMenuItem();
        jmItemProfileEdit = new javax.swing.JMenuItem();
        jmItemProfileDelete = new javax.swing.JMenuItem();
        jMenuInventory = new javax.swing.JMenu();
        jmItemInventoryDetail = new javax.swing.JMenuItem();
        jmItemInventoryIncome = new javax.swing.JMenuItem();
        jmItemInventoryEdit = new javax.swing.JMenuItem();
        jmItemInventoryOutcome = new javax.swing.JMenuItem();
        jmItemInventoryCancel = new javax.swing.JMenuItem();
        jMenuSales = new javax.swing.JMenu();
        jmItemSalesDetail = new javax.swing.JMenuItem();
        jmItemSalesCancel = new javax.swing.JMenuItem();
        jmItemSalesCashOut = new javax.swing.JMenuItem();
        jMenuCatalogs = new javax.swing.JMenu();
        jMenuCategory = new javax.swing.JMenu();
        jmItemCategoryView = new javax.swing.JMenuItem();
        jmItemCategoryCreate = new javax.swing.JMenuItem();
        jmItemCategoryEdit = new javax.swing.JMenuItem();
        jmItemCategoryDelete = new javax.swing.JMenuItem();
        jMenuProvider = new javax.swing.JMenu();
        jmItemProviderView = new javax.swing.JMenuItem();
        jmItemProviderCreate = new javax.swing.JMenuItem();
        jmItemProviderEdit = new javax.swing.JMenuItem();
        jmItemProviderDelete = new javax.swing.JMenuItem();
        jMenuProduct = new javax.swing.JMenu();
        jmItemProductView = new javax.swing.JMenuItem();
        jmItemProductCreate = new javax.swing.JMenuItem();
        jmItemProductEdit = new javax.swing.JMenuItem();
        jmItemProductDelete = new javax.swing.JMenuItem();
        jmItemNotifications = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jmItemSynchronize = new javax.swing.JMenuItem();
        jmItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainJFrame"); // NOI18N

        jpanelToolbar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));

        jbtnInventoryDetailShortcut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnInventoryDetailShortcut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stock.png"))); // NOI18N
        jbtnInventoryDetailShortcut.setText("Inventario");
        jbtnInventoryDetailShortcut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInventoryDetailShortcut.setFocusable(false);
        jbtnInventoryDetailShortcut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnInventoryDetailShortcut.setMaximumSize(new java.awt.Dimension(100, 85));
        jbtnInventoryDetailShortcut.setOpaque(false);
        jbtnInventoryDetailShortcut.setPreferredSize(new java.awt.Dimension(100, 85));
        jbtnInventoryDetailShortcut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnInventoryDetailShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInventoryDetailShortcutActionPerformed(evt);
            }
        });

        jbtnSale.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnSale.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/shopping-basket.png"))); // NOI18N
        jbtnSale.setText("Venta");
        jbtnSale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSale.setFocusable(false);
        jbtnSale.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSale.setMaximumSize(new java.awt.Dimension(100, 85));
        jbtnSale.setOpaque(false);
        jbtnSale.setPreferredSize(new java.awt.Dimension(100, 85));
        jbtnSale.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaleActionPerformed(evt);
            }
        });

        jbtnProductViewShortcut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnProductViewShortcut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N
        jbtnProductViewShortcut.setText("Articulos");
        jbtnProductViewShortcut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnProductViewShortcut.setFocusable(false);
        jbtnProductViewShortcut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnProductViewShortcut.setMaximumSize(new java.awt.Dimension(100, 85));
        jbtnProductViewShortcut.setOpaque(false);
        jbtnProductViewShortcut.setPreferredSize(new java.awt.Dimension(100, 85));
        jbtnProductViewShortcut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnProductViewShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnProductViewShortcutActionPerformed(evt);
            }
        });

        jbtnCash.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnCash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cashbox.png"))); // NOI18N
        jbtnCash.setText("Caja");
        jbtnCash.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCash.setFocusable(false);
        jbtnCash.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCash.setMaximumSize(new java.awt.Dimension(100, 85));
        jbtnCash.setOpaque(false);
        jbtnCash.setPreferredSize(new java.awt.Dimension(100, 85));
        jbtnCash.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCashActionPerformed(evt);
            }
        });

        jbtnReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pie-chart.png"))); // NOI18N
        jbtnReport.setText("Informes");
        jbtnReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnReport.setFocusable(false);
        jbtnReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnReport.setMaximumSize(new java.awt.Dimension(100, 85));
        jbtnReport.setOpaque(false);
        jbtnReport.setPreferredSize(new java.awt.Dimension(100, 85));
        jbtnReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReportActionPerformed(evt);
            }
        });

        jbtnSynchShortcut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jbtnSynchShortcut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cloud-computing.png"))); // NOI18N
        jbtnSynchShortcut.setText("Sincronizar");
        jbtnSynchShortcut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSynchShortcut.setFocusable(false);
        jbtnSynchShortcut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnSynchShortcut.setMaximumSize(new java.awt.Dimension(100, 85));
        jbtnSynchShortcut.setPreferredSize(new java.awt.Dimension(100, 85));
        jbtnSynchShortcut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtnSynchShortcut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSynchShortcutActionPerformed(evt);
            }
        });

        jlblCurrentDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlblCurrentDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblCurrentDate.setText("2016-OCT-19");

        javax.swing.GroupLayout jpanelToolbarLayout = new javax.swing.GroupLayout(jpanelToolbar);
        jpanelToolbar.setLayout(jpanelToolbarLayout);
        jpanelToolbarLayout.setHorizontalGroup(
            jpanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelToolbarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jpanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnInventoryDetailShortcut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbtnSale, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbtnProductViewShortcut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbtnCash, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbtnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jbtnSynchShortcut, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jlblCurrentDate, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        jpanelToolbarLayout.setVerticalGroup(
            jpanelToolbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelToolbarLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jbtnInventoryDetailShortcut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbtnSale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbtnProductViewShortcut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbtnCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbtnReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jbtnSynchShortcut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jlblCurrentDate)
                .addContainerGap())
        );

        desktopPane.setLayer(jpanelToolbar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(678, Short.MAX_VALUE))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuSystem.setMnemonic('a');
        jMenuSystem.setText("Archivo");
        jMenuSystem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmItemExit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemExit.setText("Salir");
        jmItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemExitActionPerformed(evt);
            }
        });
        jMenuSystem.add(jmItemExit);

        menuBar.add(jMenuSystem);

        jMenuUser.setMnemonic('u');
        jMenuUser.setText("Usuario");
        jMenuUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmItemUserView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemUserView.setText("Ver");
        jmItemUserView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemUserViewActionPerformed(evt);
            }
        });
        jMenuUser.add(jmItemUserView);

        jmItemUserCreate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemUserCreate.setText("Nuevo");
        jMenuUser.add(jmItemUserCreate);

        jmItemUserEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemUserEdit.setText("Modificar");
        jMenuUser.add(jmItemUserEdit);

        jmItemUserDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemUserDelete.setText("Eliminar");
        jMenuUser.add(jmItemUserDelete);

        menuBar.add(jMenuUser);

        jMenuProfile.setMnemonic('p');
        jMenuProfile.setText("Perfil");
        jMenuProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmItemProfileView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProfileView.setText("Ver");
        jmItemProfileView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProfileViewActionPerformed(evt);
            }
        });
        jMenuProfile.add(jmItemProfileView);

        jmItemProfileCreate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProfileCreate.setText("Nuevo");
        jmItemProfileCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProfileCreateActionPerformed(evt);
            }
        });
        jMenuProfile.add(jmItemProfileCreate);
        jmItemProfileCreate.getAccessibleContext().setAccessibleName("jMenuItemProfileCreate");

        jmItemProfileEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProfileEdit.setMnemonic('y');
        jmItemProfileEdit.setText("Modificar");
        jmItemProfileEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProfileEditActionPerformed(evt);
            }
        });
        jMenuProfile.add(jmItemProfileEdit);

        jmItemProfileDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProfileDelete.setMnemonic('p');
        jmItemProfileDelete.setText("Eliminar");
        jmItemProfileDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProfileDeleteActionPerformed(evt);
            }
        });
        jMenuProfile.add(jmItemProfileDelete);

        menuBar.add(jMenuProfile);

        jMenuInventory.setText("Inventario");
        jMenuInventory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmItemInventoryDetail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemInventoryDetail.setText("Detalle");
        jmItemInventoryDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemInventoryDetailActionPerformed(evt);
            }
        });
        jMenuInventory.add(jmItemInventoryDetail);

        jmItemInventoryIncome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemInventoryIncome.setText("Entrada");
        jmItemInventoryIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemInventoryIncomeActionPerformed(evt);
            }
        });
        jMenuInventory.add(jmItemInventoryIncome);

        jmItemInventoryEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemInventoryEdit.setText("Modificación");
        jmItemInventoryEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemInventoryEditActionPerformed(evt);
            }
        });
        jMenuInventory.add(jmItemInventoryEdit);

        jmItemInventoryOutcome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemInventoryOutcome.setText("Salida");
        jmItemInventoryOutcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemInventoryOutcomeActionPerformed(evt);
            }
        });
        jMenuInventory.add(jmItemInventoryOutcome);

        jmItemInventoryCancel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemInventoryCancel.setText("Cancelación");
        jmItemInventoryCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemInventoryCancelActionPerformed(evt);
            }
        });
        jMenuInventory.add(jmItemInventoryCancel);

        menuBar.add(jMenuInventory);

        jMenuSales.setText("Ventas");
        jMenuSales.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmItemSalesDetail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemSalesDetail.setText("Detalle");
        jmItemSalesDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalesDetailActionPerformed(evt);
            }
        });
        jMenuSales.add(jmItemSalesDetail);

        jmItemSalesCancel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemSalesCancel.setText("Cancelación");
        jmItemSalesCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalesCancelActionPerformed(evt);
            }
        });
        jMenuSales.add(jmItemSalesCancel);

        jmItemSalesCashOut.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemSalesCashOut.setText("Cortes");
        jmItemSalesCashOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemSalesCashOutActionPerformed(evt);
            }
        });
        jMenuSales.add(jmItemSalesCashOut);

        menuBar.add(jMenuSales);

        jMenuCatalogs.setMnemonic('h');
        jMenuCatalogs.setText("Catálogo");
        jMenuCatalogs.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuCategory.setText("Categoría");
        jMenuCategory.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jmItemCategoryView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemCategoryView.setText("Ver");
        jmItemCategoryView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCategoryViewActionPerformed(evt);
            }
        });
        jMenuCategory.add(jmItemCategoryView);

        jmItemCategoryCreate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemCategoryCreate.setText("Nuevo");
        jmItemCategoryCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCategoryCreateActionPerformed(evt);
            }
        });
        jMenuCategory.add(jmItemCategoryCreate);

        jmItemCategoryEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemCategoryEdit.setText("Modificar");
        jmItemCategoryEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemCategoryEditActionPerformed(evt);
            }
        });
        jMenuCategory.add(jmItemCategoryEdit);

        jmItemCategoryDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemCategoryDelete.setText("Eliminar");
        jMenuCategory.add(jmItemCategoryDelete);

        jMenuCatalogs.add(jMenuCategory);

        jMenuProvider.setText("Proveedor");
        jMenuProvider.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jmItemProviderView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProviderView.setText("Ver");
        jmItemProviderView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProviderViewActionPerformed(evt);
            }
        });
        jMenuProvider.add(jmItemProviderView);

        jmItemProviderCreate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProviderCreate.setText("Nuevo");
        jmItemProviderCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProviderCreateActionPerformed(evt);
            }
        });
        jMenuProvider.add(jmItemProviderCreate);

        jmItemProviderEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProviderEdit.setText("Modificar");
        jmItemProviderEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProviderEditActionPerformed(evt);
            }
        });
        jMenuProvider.add(jmItemProviderEdit);

        jmItemProviderDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProviderDelete.setText("Eliminar");
        jMenuProvider.add(jmItemProviderDelete);

        jMenuCatalogs.add(jMenuProvider);

        jMenuProduct.setText("Artículo");
        jMenuProduct.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jmItemProductView.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProductView.setText("Ver");
        jmItemProductView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProductViewActionPerformed(evt);
            }
        });
        jMenuProduct.add(jmItemProductView);

        jmItemProductCreate.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProductCreate.setText("Nuevo");
        jmItemProductCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProductCreateActionPerformed(evt);
            }
        });
        jMenuProduct.add(jmItemProductCreate);

        jmItemProductEdit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProductEdit.setText("Modificar");
        jmItemProductEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmItemProductEditActionPerformed(evt);
            }
        });
        jMenuProduct.add(jmItemProductEdit);

        jmItemProductDelete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemProductDelete.setText("Eliminar");
        jMenuProduct.add(jmItemProductDelete);

        jMenuCatalogs.add(jMenuProduct);

        jmItemNotifications.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemNotifications.setText("Notificaciones");
        jMenuCatalogs.add(jmItemNotifications);

        menuBar.add(jMenuCatalogs);

        jMenuHelp.setMnemonic('h');
        jMenuHelp.setText("Ayuda");
        jMenuHelp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jmItemSynchronize.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemSynchronize.setText("Sincronzación");
        jMenuHelp.add(jmItemSynchronize);

        jmItemAbout.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jmItemAbout.setMnemonic('a');
        jmItemAbout.setText("Acerca de");
        jMenuHelp.add(jmItemAbout);

        menuBar.add(jMenuHelp);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        getAccessibleContext().setAccessibleName("mainJFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmItemProfileCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProfileCreateActionPerformed
        ProfileCreateJFrame pCreateJFrame = new ProfileCreateJFrame();
        desktopPane.add(pCreateJFrame);
        pCreateJFrame.pack();
        try {
            pCreateJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pCreateJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemProfileCreateActionPerformed

    private void jmItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmItemExitActionPerformed

    private void jmItemProfileViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProfileViewActionPerformed
        ProfileViewJFrame pViewJFrame = new ProfileViewJFrame();
        desktopPane.add(pViewJFrame);
        pViewJFrame.pack();
        try {
            pViewJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pViewJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemProfileViewActionPerformed

    private void jmItemProfileEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProfileEditActionPerformed
        ProfileEditJFrame pEditJFrame = new ProfileEditJFrame();
        desktopPane.add(pEditJFrame);
        pEditJFrame.pack();
        try {
            pEditJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pEditJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemProfileEditActionPerformed

    private void jmItemProfileDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProfileDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemProfileDeleteActionPerformed

    private void jmItemUserViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemUserViewActionPerformed
        UserViewJFrame uViewJFrame = new UserViewJFrame();
        desktopPane.add(uViewJFrame);
        uViewJFrame.pack();
        try {
            uViewJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        uViewJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemUserViewActionPerformed

    private void jmItemProviderCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProviderCreateActionPerformed
        ProviderCreateJFrame pCreateJForm = new ProviderCreateJFrame();
        desktopPane.add(pCreateJForm);
        pCreateJForm.pack();
        try {
            pCreateJForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pCreateJForm.setVisible(true);
    }//GEN-LAST:event_jmItemProviderCreateActionPerformed

    private void jmItemProviderViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProviderViewActionPerformed
        ProviderViewJFrame pViewJForm = new ProviderViewJFrame();
        desktopPane.add(pViewJForm);
        pViewJForm.pack();
        try {
            pViewJForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pViewJForm.setVisible(true);
    }//GEN-LAST:event_jmItemProviderViewActionPerformed

    private void jmItemProviderEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProviderEditActionPerformed
        ProviderEditJFrame pEditJForm = new ProviderEditJFrame();
        desktopPane.add(pEditJForm);
        pEditJForm.pack();
        try {
            pEditJForm.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pEditJForm.setVisible(true);
    }//GEN-LAST:event_jmItemProviderEditActionPerformed

    private void jmItemCategoryViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCategoryViewActionPerformed
        CategoryViewJFrame cViewJFrame = new CategoryViewJFrame();
        desktopPane.add(cViewJFrame);
        cViewJFrame.pack();
        try {
            cViewJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        cViewJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemCategoryViewActionPerformed

    private void jmItemCategoryCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCategoryCreateActionPerformed
        CategoryCreateJFrame cCreateJFrame = new CategoryCreateJFrame();
        desktopPane.add(cCreateJFrame);
        cCreateJFrame.pack();
        try {
            cCreateJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        cCreateJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemCategoryCreateActionPerformed

    private void jmItemCategoryEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemCategoryEditActionPerformed
        CategoryEditJFrame cEditJFrame = new CategoryEditJFrame();
        desktopPane.add(cEditJFrame);
        cEditJFrame.pack();
        try {
            cEditJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        cEditJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemCategoryEditActionPerformed

    private void jmItemProductViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProductViewActionPerformed
        ProductViewJFrame pViewJFrame = new ProductViewJFrame();
        desktopPane.add(pViewJFrame);
        pViewJFrame.pack();
        try {
            pViewJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pViewJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemProductViewActionPerformed

    private void jmItemProductCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProductCreateActionPerformed
        ProductCreateJFrame pCreateJFrame = new ProductCreateJFrame();
        desktopPane.add(pCreateJFrame);
        pCreateJFrame.pack();
        try {
            pCreateJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pCreateJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemProductCreateActionPerformed

    private void jmItemProductEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemProductEditActionPerformed
        ProductEditJFrame pEditJFrame = new ProductEditJFrame();
        desktopPane.add(pEditJFrame);
        pEditJFrame.pack();
        try {
            pEditJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        pEditJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemProductEditActionPerformed

    private void jmItemInventoryDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemInventoryDetailActionPerformed
        
        if (isWindowOpened(InventoryDetailJFrame.class))
        {
            InventoryDetailJFrame window =
                (InventoryDetailJFrame) getWindow(InventoryDetailJFrame.class);
            window.toFront();
            window.requestFocus();
            return;
        }
        
        InventoryDetailJFrame inventoryDetailJFrame = new InventoryDetailJFrame();
        desktopPane.add(inventoryDetailJFrame);
        inventoryDetailJFrame.pack();
        try {
            inventoryDetailJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        inventoryDetailJFrame.setVisible(true);
        
    }//GEN-LAST:event_jmItemInventoryDetailActionPerformed

    private void jmItemInventoryIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemInventoryIncomeActionPerformed
                
        if (isWindowOpened(InventoryIncomeJFrame.class))
        {
            InventoryIncomeJFrame window =
                (InventoryIncomeJFrame) getWindow(InventoryIncomeJFrame.class);
            window.toFront();
            window.requestFocus();
            return;
        }
        
        InventoryIncomeJFrame inventoryIncomeJFrame = new InventoryIncomeJFrame();
        desktopPane.add(inventoryIncomeJFrame);
        inventoryIncomeJFrame.pack();
        try {
            inventoryIncomeJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        inventoryIncomeJFrame.setVisible(true);
        
    }//GEN-LAST:event_jmItemInventoryIncomeActionPerformed

    private void jmItemInventoryEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemInventoryEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemInventoryEditActionPerformed

    private void jmItemInventoryOutcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemInventoryOutcomeActionPerformed
        
        if (isWindowOpened(InventoryOutcomeJFrame.class))
        {
            InventoryOutcomeJFrame window =
                (InventoryOutcomeJFrame) getWindow(InventoryOutcomeJFrame.class);
            window.toFront();
            window.requestFocus();
            return;
        }
        
        InventoryOutcomeJFrame inventoryOutcomeJFrame = new InventoryOutcomeJFrame();
        desktopPane.add(inventoryOutcomeJFrame);
        inventoryOutcomeJFrame.pack();
        try {
            inventoryOutcomeJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        inventoryOutcomeJFrame.setVisible(true);
    }//GEN-LAST:event_jmItemInventoryOutcomeActionPerformed

    private void jmItemInventoryCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemInventoryCancelActionPerformed
        
        if (isWindowOpened(InventoryCancelJFrame.class))
        {
            InventoryCancelJFrame window =
                (InventoryCancelJFrame) getWindow(InventoryCancelJFrame.class);
            window.toFront();
            window.requestFocus();
            return;
        }
        
        InventoryCancelJFrame inventoryCancelJFrame = new InventoryCancelJFrame();
        desktopPane.add(inventoryCancelJFrame);
        inventoryCancelJFrame.pack();
        try {
            inventoryCancelJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        inventoryCancelJFrame.setVisible(true);
        
    }//GEN-LAST:event_jmItemInventoryCancelActionPerformed

    private void jmItemSalesDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalesDetailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemSalesDetailActionPerformed

    private void jmItemSalesCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalesCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemSalesCancelActionPerformed

    private void jmItemSalesCashOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmItemSalesCashOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmItemSalesCashOutActionPerformed

    private void jbtnInventoryDetailShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInventoryDetailShortcutActionPerformed
        
        if (isWindowOpened(InventoryDetailJFrame.class))
        {
            InventoryDetailJFrame window =
                (InventoryDetailJFrame) getWindow(InventoryDetailJFrame.class);
            window.toFront();
            window.requestFocus();
            return;
        }
        
        InventoryDetailJFrame inventoryDetailJFrame = new InventoryDetailJFrame();
        desktopPane.add(inventoryDetailJFrame);
        inventoryDetailJFrame.pack();
        try {
            inventoryDetailJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        inventoryDetailJFrame.setVisible(true);
        
    }//GEN-LAST:event_jbtnInventoryDetailShortcutActionPerformed

    private void jbtnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaleActionPerformed
        
        /*SalesJFrame salesJFrame = new SalesJFrame();
        salesJFrame.pack();
        /**/
        
        //GraphicsDevice graphicsDevice;
        //GraphicsEnvironment graphicsEnvironment = GraphicsEnvironment.getLocalGraphicsEnvironment();
        //graphicsDevice = graphicsEnvironment.getDefaultScreenDevice();
        
        SalesJFrame salesJFrame = new SalesJFrame();
        //salesJFrame.pack();
        //graphicsDevice.setFullScreenWindow(salesJFrame);
        
    }//GEN-LAST:event_jbtnSaleActionPerformed

    private void jbtnProductViewShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnProductViewShortcutActionPerformed
        ProductViewJFrame productViewJFrame = new ProductViewJFrame();
        desktopPane.add(productViewJFrame);
        productViewJFrame.pack();
        try {
            productViewJFrame.setMaximum(true);
        } catch (PropertyVetoException ex) {
            logger.error("Error setting maximum", ex);
        }
        productViewJFrame.setVisible(true);
    }//GEN-LAST:event_jbtnProductViewShortcutActionPerformed

    private void jbtnCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCashActionPerformed

    private void jbtnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnReportActionPerformed

    private void jbtnSynchShortcutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSynchShortcutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnSynchShortcutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            javax.swing.UIManager.getLookAndFeelDefaults().put("Table.alternateRowColor", java.awt.Color.lightGray);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenuCatalogs;
    private javax.swing.JMenu jMenuCategory;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenu jMenuInventory;
    private javax.swing.JMenu jMenuProduct;
    private javax.swing.JMenu jMenuProfile;
    private javax.swing.JMenu jMenuProvider;
    private javax.swing.JMenu jMenuSales;
    private javax.swing.JMenu jMenuSystem;
    private javax.swing.JMenu jMenuUser;
    private javax.swing.JButton jbtnCash;
    private javax.swing.JButton jbtnInventoryDetailShortcut;
    private javax.swing.JButton jbtnProductViewShortcut;
    private javax.swing.JButton jbtnReport;
    private javax.swing.JButton jbtnSale;
    private javax.swing.JButton jbtnSynchShortcut;
    private javax.swing.JLabel jlblCurrentDate;
    private javax.swing.JMenuItem jmItemAbout;
    private javax.swing.JMenuItem jmItemCategoryCreate;
    private javax.swing.JMenuItem jmItemCategoryDelete;
    private javax.swing.JMenuItem jmItemCategoryEdit;
    private javax.swing.JMenuItem jmItemCategoryView;
    private javax.swing.JMenuItem jmItemExit;
    private javax.swing.JMenuItem jmItemInventoryCancel;
    private javax.swing.JMenuItem jmItemInventoryDetail;
    private javax.swing.JMenuItem jmItemInventoryEdit;
    private javax.swing.JMenuItem jmItemInventoryIncome;
    private javax.swing.JMenuItem jmItemInventoryOutcome;
    private javax.swing.JMenuItem jmItemNotifications;
    private javax.swing.JMenuItem jmItemProductCreate;
    private javax.swing.JMenuItem jmItemProductDelete;
    private javax.swing.JMenuItem jmItemProductEdit;
    private javax.swing.JMenuItem jmItemProductView;
    private javax.swing.JMenuItem jmItemProfileCreate;
    private javax.swing.JMenuItem jmItemProfileDelete;
    private javax.swing.JMenuItem jmItemProfileEdit;
    private javax.swing.JMenuItem jmItemProfileView;
    private javax.swing.JMenuItem jmItemProviderCreate;
    private javax.swing.JMenuItem jmItemProviderDelete;
    private javax.swing.JMenuItem jmItemProviderEdit;
    private javax.swing.JMenuItem jmItemProviderView;
    private javax.swing.JMenuItem jmItemSalesCancel;
    private javax.swing.JMenuItem jmItemSalesCashOut;
    private javax.swing.JMenuItem jmItemSalesDetail;
    private javax.swing.JMenuItem jmItemSynchronize;
    private javax.swing.JMenuItem jmItemUserCreate;
    private javax.swing.JMenuItem jmItemUserDelete;
    private javax.swing.JMenuItem jmItemUserEdit;
    private javax.swing.JMenuItem jmItemUserView;
    private javax.swing.JPanel jpanelToolbar;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
