/*
 * Copyright (C) 2016 Milton Cavazos
 *
 * Este programa es de código libre; usted podrá instalar y/o
 * utilizar una copia del programa de computación en una computadora compatible,
 * limitándose al número permitido de computadoras.
 */
package dis.software.pos.jforms;

import dis.software.pos.Application;
import dis.software.pos.ApplicationSession;
import dis.software.pos.combobox.model.CategoryComboBoxModel;
import dis.software.pos.combobox.model.ProductComboBoxModel;
import dis.software.pos.combobox.model.ProviderComboBoxModel;
import dis.software.pos.combobox.renderers.CategoryComboBoxRenderer;
import dis.software.pos.combobox.renderers.ProductComboBoxRenderer;
import dis.software.pos.combobox.renderers.ProviderComboBoxRenderer;
import dis.software.pos.entities.Category;
import dis.software.pos.entities.Product;
import dis.software.pos.entities.Provider;
import dis.software.pos.interfaces.ICategory;
import dis.software.pos.interfaces.IProduct;
import dis.software.pos.interfaces.IProvider;
import java.awt.event.ItemEvent;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Formulario para la modificación de productos
 * @author Milton Cavazos
 */
public class ProductEditJFrame extends javax.swing.JInternalFrame
{

    /**
     * Creación de nuevo formulario ProductEditJFrame
     */
    public ProductEditJFrame()
    {
        initComponents();
        
        IProduct iProduct = Application.getContext().getBean(IProduct.class);
        List<Product> products = iProduct.findAll();
        products.add(0, new Product("", "Elige un producto", ""));
        jcboProduct.setModel(new ProductComboBoxModel(products));
        jcboProduct.setRenderer(new ProductComboBoxRenderer());
        
        jcboProduct.addItemListener((ItemEvent e) ->
        {
            //Objeto afectado por el evento
            if (!(e.getItem() instanceof Product))
            {
                jtxtCode.setText("");
                jtxtName.setText("");
                jtxtDescription.setText("");
                jtxtPrice.setText("");
                jtxtCost.setText("");
                jtxtQuantityByUnit.setText("");
                jtxtUnitsInStock.setText("");
                jcboCategory.setSelectedIndex(0);
                jcboProvider.setSelectedIndex(0);
                return;
            }
            Product product = (Product) e.getItem();
            if (e.getStateChange() == ItemEvent.SELECTED
                && product.getId() != null)
            {
                jtxtCode.setText(product.getCode());
                jtxtName.setText(product.getName());
                jtxtDescription.setText(product.getDescription());
                jtxtPrice.setText(product.getPrice().toString());
                jtxtCost.setText(product.getCost().toString());
                jtxtQuantityByUnit.setText(product.getQuantityByUnit().toString());
                jtxtUnitsInStock.setText(product.getUnitsInStock().toString());
                jcboCategory.setSelectedItem(product.getCategory());
                jcboProvider.setSelectedItem(product.getProvider());
            }
        });
        
        ICategory iCategory = Application.getContext().getBean(ICategory.class);
        List<Category> categories = iCategory.findAll();
        categories.add(0, new Category("", "Elige una categoría", ""));
        jcboCategory.setModel(new CategoryComboBoxModel(categories));
        jcboCategory.setRenderer(new CategoryComboBoxRenderer());
        
        IProvider iProvider = Application.getContext().getBean(IProvider.class);
        List<Provider> providers = iProvider.findAll();
        providers.add(0, new Provider("", "Elige un proveedor", ""));
        jcboProvider.setModel(new ProviderComboBoxModel(providers));
        jcboProvider.setRenderer(new ProviderComboBoxRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelHeader = new javax.swing.JPanel();
        jlblHeader = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jsepHeader = new javax.swing.JSeparator();
        jcboProduct = new javax.swing.JComboBox<>();
        jlblProduct = new javax.swing.JLabel();
        jtxtCode = new javax.swing.JTextField();
        jlblCode = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jlblName = new javax.swing.JLabel();
        jtxtDescription = new javax.swing.JTextField();
        jlblDescription = new javax.swing.JLabel();
        jtxtPrice = new javax.swing.JTextField();
        jlblPrice = new javax.swing.JLabel();
        jtxtCost = new javax.swing.JTextField();
        jlblCost = new javax.swing.JLabel();
        jtxtQuantityByUnit = new javax.swing.JTextField();
        jlblQuantityByUnit = new javax.swing.JLabel();
        jtxtUnitsInStock = new javax.swing.JTextField();
        jlblUnitsInStock = new javax.swing.JLabel();
        jcboCategory = new javax.swing.JComboBox<>();
        jlblCategory = new javax.swing.JLabel();
        jcboProvider = new javax.swing.JComboBox<>();
        jlblProvider = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Modificar productos");

        jlblHeader.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jlblHeader.setForeground(new java.awt.Color(102, 102, 102));
        jlblHeader.setText("Modificar producto");

        jbtnSave.setBackground(new java.awt.Color(17, 157, 17));
        jbtnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSave.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSave.setText("Guardar");
        jbtnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSaveMouseClicked(evt);
            }
        });

        jbtnCancel.setBackground(new java.awt.Color(204, 204, 204));
        jbtnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCancel.setForeground(new java.awt.Color(0, 0, 0));
        jbtnCancel.setText("Cancelar");
        jbtnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpanelHeaderLayout = new javax.swing.GroupLayout(jpanelHeader);
        jpanelHeader.setLayout(jpanelHeaderLayout);
        jpanelHeaderLayout.setHorizontalGroup(
            jpanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(jbtnSave)
                .addGap(18, 18, 18)
                .addComponent(jbtnCancel)
                .addContainerGap())
        );
        jpanelHeaderLayout.setVerticalGroup(
            jpanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblHeader))
                .addContainerGap())
        );

        jsepHeader.setBackground(new java.awt.Color(0, 0, 0));
        jsepHeader.setForeground(new java.awt.Color(0, 0, 0));
        jsepHeader.setOpaque(true);

        jcboProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblProduct.setText("Producto");

        jtxtCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCode.setText("* Código:");

        jtxtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblName.setText("* Nombre de categoría:");

        jtxtDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblDescription.setText("Descripción:");

        jtxtPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblPrice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblPrice.setText("* Precio:");

        jtxtCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblCost.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCost.setText("* Costo:");

        jtxtQuantityByUnit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblQuantityByUnit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblQuantityByUnit.setText("* Cantidad por unidad:");

        jtxtUnitsInStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblUnitsInStock.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblUnitsInStock.setText("* Unidades en inventario:");

        jcboCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCategory.setText("Categoría");

        jcboProvider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblProvider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblProvider.setText("Proveedor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jsepHeader))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblDescription)
                            .addComponent(jlblName)
                            .addComponent(jlblCode)
                            .addComponent(jlblProduct)
                            .addComponent(jlblPrice)
                            .addComponent(jlblCost)
                            .addComponent(jlblQuantityByUnit)
                            .addComponent(jlblUnitsInStock)
                            .addComponent(jlblCategory)
                            .addComponent(jlblProvider))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcboProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtDescription)
                            .addComponent(jtxtCode)
                            .addComponent(jtxtName, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jtxtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jtxtCost)
                            .addComponent(jtxtQuantityByUnit)
                            .addComponent(jtxtUnitsInStock)
                            .addComponent(jcboCategory, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcboProvider, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsepHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblProduct))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblName)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDescription)
                    .addComponent(jtxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPrice)
                    .addComponent(jtxtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblCost)
                    .addComponent(jtxtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblQuantityByUnit)
                    .addComponent(jtxtQuantityByUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUnitsInStock)
                    .addComponent(jtxtUnitsInStock, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCategory))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblProvider))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSaveMouseClicked

        if (jtxtCode.getText().isEmpty()
            || jtxtName.getText().isEmpty()
            || jtxtPrice.getText().isEmpty()
            || jtxtCost.getText().isEmpty()
            || jtxtQuantityByUnit.getText().isEmpty()
            || jtxtUnitsInStock.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Por favor ingresa los datos marcados con un asterisco "
                + "para guardar el producto.");
            return;
        }
        if (jcboCategory.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(this, "Por favor selecciona una categoría "
                + "para guardar el producto.");
            return;
        }
        if (jcboProvider.getSelectedIndex() == 0)
        {
            JOptionPane.showMessageDialog(this, "Por favor selecciona un proveedor "
                + "para guardar el producto.");
            return;
        }
        if (!jtxtPrice.getText().matches("^[0-9]+(\\.[0-9]{1,2})?$"))
        {
            JOptionPane.showMessageDialog(this, "Solo se permiten números en el campo Precio.");
            return;
        }
        if (!jtxtCost.getText().matches("^[0-9]+(\\.[0-9]{1,2})?$"))
        {
            JOptionPane.showMessageDialog(this, "Solo se permiten números en el campo Costo.");
            return;
        }
        if (!jtxtQuantityByUnit.getText().matches("^[0-9]+(\\.[0-9]{1,2})?$"))
        {
            JOptionPane.showMessageDialog(this, "Solo se permiten números en el campo Cantidad por unidad.");
            return;
        }
        if (!jtxtUnitsInStock.getText().matches("^[0-9]+(\\.[0-9]{1,2})?$"))
        {
            JOptionPane.showMessageDialog(this, "Solo se permiten números en el campo Unidades en inventario.");
            return;
        }
        
        Product product = (Product) jcboProduct.getSelectedItem();
        //product.setCode(jtxtCode.getText());
        product.setName(jtxtName.getText());
        product.setDescription(jtxtDescription.getText());
        product.setPrice(new Double(jtxtPrice.getText()));
        product.setCost(new Double(jtxtCost.getText()));
        product.setQuantityByUnit(new Integer(jtxtQuantityByUnit.getText()));
        product.setUnitsInStock(new Integer(jtxtUnitsInStock.getText()));
        product.setUpdatedBy(ApplicationSession.getUser().getId());
        product.setUpdatedDate(new GregorianCalendar());
        product.setCategory((Category) jcboCategory.getSelectedItem());
        product.setProvider((Provider) jcboProvider.getSelectedItem());

        IProduct iProduct = Application.getContext().getBean(IProduct.class);
        iProduct.update(product);
        iProduct.flush();

        if (product.getId() != null)
        {
            JOptionPane.showMessageDialog(this, "El producto se ha actualizado exitosamente.");

            List<Product> list = iProduct.findAll();
            list.add(0, new Product("", "Elige un producto", ""));
            jcboProduct.setModel(new ProductComboBoxModel(list));

            jtxtCode.setText("");
            jtxtName.setText("");
            jtxtDescription.setText("");
            jtxtPrice.setText("");
            jtxtCost.setText("");
            jtxtQuantityByUnit.setText("");
            jtxtUnitsInStock.setText("");
            jcboCategory.setSelectedIndex(0);
            jcboProvider.setSelectedIndex(0);
        }
        
    }//GEN-LAST:event_jbtnSaveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JComboBox<Category> jcboCategory;
    private javax.swing.JComboBox<Product> jcboProduct;
    private javax.swing.JComboBox<Provider> jcboProvider;
    private javax.swing.JLabel jlblCategory;
    private javax.swing.JLabel jlblCode;
    private javax.swing.JLabel jlblCost;
    private javax.swing.JLabel jlblDescription;
    private javax.swing.JLabel jlblHeader;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPrice;
    private javax.swing.JLabel jlblProduct;
    private javax.swing.JLabel jlblProvider;
    private javax.swing.JLabel jlblQuantityByUnit;
    private javax.swing.JLabel jlblUnitsInStock;
    private javax.swing.JPanel jpanelHeader;
    private javax.swing.JSeparator jsepHeader;
    private javax.swing.JTextField jtxtCode;
    private javax.swing.JTextField jtxtCost;
    private javax.swing.JTextField jtxtDescription;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPrice;
    private javax.swing.JTextField jtxtQuantityByUnit;
    private javax.swing.JTextField jtxtUnitsInStock;
    // End of variables declaration//GEN-END:variables
}
