/*
 * Copyright (C) 2016 Milton Cavazos
 *
 * Este programa es de código libre; usted podrá instalar y/o
 * utilizar una copia del programa de computación en una computadora compatible,
 * limitándose al número permitido de computadoras.
 */
package dis.software.pos.jforms;

import dis.software.pos.Application;
import dis.software.pos.ApplicationSession;
import dis.software.pos.combobox.model.ProviderComboBoxModel;
import dis.software.pos.combobox.renderers.ProviderComboBoxRenderer;
import dis.software.pos.entities.Provider;
import dis.software.pos.interfaces.IProvider;
import java.awt.event.ItemEvent;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Formulario para la modificación de proveedores
 * @author Milton Cavazos
 */
public class ProviderEditJFrame extends javax.swing.JInternalFrame {

    /**
     * Creación de nuevo formulario ProviderEditJFrame
     */
    public ProviderEditJFrame()
    {
        initComponents();
        
        IProvider iProvider = Application.getContext().getBean(IProvider.class);
        List<Provider> list = iProvider.findAll();
        list.add(0, new Provider("", "Elige un proveedor", ""));
        jcboProvider.setModel(new ProviderComboBoxModel(list));
        jcboProvider.setRenderer(new ProviderComboBoxRenderer());
        
        jcboProvider.addItemListener((ItemEvent e) ->
        {
            if (!(e.getItem() instanceof Provider))
            {
                jtxtCode.setText("");
                jtxtName.setText("");
                jtxtDescription.setText("");
                jcboCountry.setSelectedIndex(0);
                jcboState.setSelectedIndex(0);
                jcboCity.setSelectedIndex(0);
                jtxtAddress.setText("");
                jtxtPostalCode.setText("");
                jtxtPhone.setText("");
                return;
            }
            Provider provider = (Provider) e.getItem();
            if (e.getStateChange() == ItemEvent.SELECTED
                && provider.getId() != null)
            {
                jtxtCode.setText(provider.getCode());
                jtxtName.setText(provider.getName());
                jtxtDescription.setText(provider.getDescription());
                jcboCountry.setSelectedItem(provider.getCountry());
                jcboState.setSelectedItem(provider.getState());
                jcboCity.setSelectedItem(provider.getCity());
                jtxtAddress.setText(provider.getAddress());
                jtxtPostalCode.setText(provider.getPostalCode());
                jtxtPhone.setText(provider.getPhone());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelHeader = new javax.swing.JPanel();
        jlblHeader = new javax.swing.JLabel();
        jbtnSave = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jsepHeader = new javax.swing.JSeparator();
        jcboProvider = new javax.swing.JComboBox<>();
        jlblProfile = new javax.swing.JLabel();
        jtxtCode = new javax.swing.JTextField();
        jlblCode = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jlblName = new javax.swing.JLabel();
        jtxtDescription = new javax.swing.JTextField();
        jlblDescription = new javax.swing.JLabel();
        jlblState = new javax.swing.JLabel();
        jcboCity = new javax.swing.JComboBox<>();
        jlblCity = new javax.swing.JLabel();
        jtxtAddress = new javax.swing.JTextField();
        jlblAddress = new javax.swing.JLabel();
        jtxtPostalCode = new javax.swing.JTextField();
        jlblPostalCode = new javax.swing.JLabel();
        jtxtPhone = new javax.swing.JTextField();
        jcboCountry = new javax.swing.JComboBox<>();
        jlblPhone = new javax.swing.JLabel();
        jlblCountry = new javax.swing.JLabel();
        jcboState = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Modificar proveedores");

        jlblHeader.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jlblHeader.setForeground(new java.awt.Color(102, 102, 102));
        jlblHeader.setText("Modificar proveedor");

        jbtnSave.setBackground(new java.awt.Color(17, 157, 17));
        jbtnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnSave.setForeground(new java.awt.Color(255, 255, 255));
        jbtnSave.setText("Guardar");
        jbtnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSaveMouseClicked(evt);
            }
        });

        jbtnCancel.setBackground(new java.awt.Color(204, 204, 204));
        jbtnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCancel.setForeground(new java.awt.Color(0, 0, 0));
        jbtnCancel.setText("Cancelar");
        jbtnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jpanelHeaderLayout = new javax.swing.GroupLayout(jpanelHeader);
        jpanelHeader.setLayout(jpanelHeaderLayout);
        jpanelHeaderLayout.setHorizontalGroup(
            jpanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelHeaderLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                .addComponent(jbtnSave)
                .addGap(18, 18, 18)
                .addComponent(jbtnCancel)
                .addContainerGap())
        );
        jpanelHeaderLayout.setVerticalGroup(
            jpanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblHeader))
                .addContainerGap())
        );

        jsepHeader.setBackground(new java.awt.Color(0, 0, 0));
        jsepHeader.setForeground(new java.awt.Color(0, 0, 0));
        jsepHeader.setOpaque(true);

        jcboProvider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblProfile.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblProfile.setText("Proveedor");

        jtxtCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCode.setText("* Código:");

        jtxtName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblName.setText("* Nombre de proveedor:");

        jtxtDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblDescription.setText("Descripción:");

        jlblState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblState.setText("Estado:");

        jcboCity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcboCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige una ciudad", "Guadalupe" }));
        jcboCity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlblCity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCity.setText("Ciudad:");

        jtxtAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblAddress.setText("Dirección:");

        jtxtPostalCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jlblPostalCode.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblPostalCode.setText("Código postal:");

        jtxtPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jcboCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcboCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un pais", "Mexico" }));
        jcboCountry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlblPhone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblPhone.setText("Teléfono:");

        jlblCountry.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlblCountry.setText("Pais:");

        jcboState.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jcboState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elige un estado", "Nuevo León" }));
        jcboState.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsepHeader)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblAddress)
                            .addComponent(jlblPostalCode)
                            .addComponent(jlblPhone)
                            .addComponent(jlblCountry)
                            .addComponent(jlblState)
                            .addComponent(jlblCity))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcboCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtPostalCode)
                            .addComponent(jcboState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcboCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblDescription)
                            .addComponent(jlblName)
                            .addComponent(jlblCode)
                            .addComponent(jlblProfile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcboProvider, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtDescription)
                            .addComponent(jtxtCode)
                            .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jsepHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblProfile))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblName)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDescription)
                    .addComponent(jtxtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCountry))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboState, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblState))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcboCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblCity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblAddress))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPostalCode))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPhone))
                .addGap(0, 66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSaveMouseClicked

        if (jtxtCode.getText().isEmpty() || jtxtName.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Por favor ingresa un código y un nombre para guardar el proveedor.");
            return;
        }
        Provider provider = (Provider) jcboProvider.getSelectedItem();
        //profile.setCode(jtxtCode.getText());
        provider.setName(jtxtName.getText());
        provider.setDescription(jtxtDescription.getText());
        provider.setCountry(jcboCountry.getSelectedItem().toString());
        provider.setState(jcboState.getSelectedItem().toString());
        provider.setCity(jcboCity.getSelectedItem().toString());
        provider.setAddress(jtxtAddress.getText());
        provider.setPostalCode(jtxtPostalCode.getText());
        provider.setPhone(jtxtPhone.getText());
        provider.setUpdatedBy(ApplicationSession.getUser().getId());
        provider.setUpdatedDate(new Date());

        IProvider iProvider = Application.getContext().getBean(IProvider.class);
        iProvider.update(provider);
        iProvider.flush();

        if (provider.getId() != null)
        {
            JOptionPane.showMessageDialog(this, "El proveedor se ha actualizado exitosamente.");
            
            List<Provider> list = iProvider.findAll();
            list.add(0, new Provider("", "Elige un proveedor", ""));
            jcboProvider.setModel(new ProviderComboBoxModel(list));
            
            jtxtCode.setText("");
            jtxtName.setText("");
            jtxtDescription.setText("");
            jcboCountry.setSelectedIndex(0);
            jcboState.setSelectedIndex(0);
            jcboCity.setSelectedIndex(0);
            jtxtAddress.setText("");
            jtxtPostalCode.setText("");
            jtxtPhone.setText("");
        }
    }//GEN-LAST:event_jbtnSaveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JComboBox<String> jcboCity;
    private javax.swing.JComboBox<String> jcboCountry;
    private javax.swing.JComboBox<Provider> jcboProvider;
    private javax.swing.JComboBox<String> jcboState;
    private javax.swing.JLabel jlblAddress;
    private javax.swing.JLabel jlblCity;
    private javax.swing.JLabel jlblCode;
    private javax.swing.JLabel jlblCountry;
    private javax.swing.JLabel jlblDescription;
    private javax.swing.JLabel jlblHeader;
    private javax.swing.JLabel jlblName;
    private javax.swing.JLabel jlblPhone;
    private javax.swing.JLabel jlblPostalCode;
    private javax.swing.JLabel jlblProfile;
    private javax.swing.JLabel jlblState;
    private javax.swing.JPanel jpanelHeader;
    private javax.swing.JSeparator jsepHeader;
    private javax.swing.JTextField jtxtAddress;
    private javax.swing.JTextField jtxtCode;
    private javax.swing.JTextField jtxtDescription;
    private javax.swing.JTextField jtxtName;
    private javax.swing.JTextField jtxtPhone;
    private javax.swing.JTextField jtxtPostalCode;
    // End of variables declaration//GEN-END:variables
}
